# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
#pipeline: supervised_embeddings
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DucklingHTTPExtractor
    url: http://duckling_server:8000
    dimensions:
      - number
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100  
